# Configuration for BSides Oslo 2020 website. This
# file contains most of the variables for the information on the website.

title: BSides Oslo 2020
date: November 23th, 2020
location: "Vulkan Arena"

description: "BSides Oslo is an inclusive community driven information security event. The second annual event will be held in November."

baseurl: ""

twitter_username: OsloBSides

forms:
  cfp: https://forms.gle/1PgjNGRGTNGo9gWZ6 

emails:
  info: info@bsidesoslo.no
  sponsors: sponsors@bsidesoslo.no
  cfp: cfp@bsidesoslo.no

social:
- title: twitter
  url: https://twitter.com/OsloBSides
- title: youtube
  url: https://www.youtube.com/channel/UC6kTOacrQTu1ahmRCvXhhrA
- title: envelope
  url: mailto:info@bsidesoslo.no

# Build settings

exclude: 
- README.md
- LICENSE
- Dockerfile
- CNAME

menu:
- title: CFP
  url: "/#cfp"
- title: Sponsorship
  url: "/#sponsors"
- title: About
  url: "/#about"
- title: Team
  url:  "/#team"
- title: Code of Conduct
  url: "/code-of-conduct"

